@startuml tictactoe
abstract class AI {
	- difficulty : String
	# maximizing : boolean
	+ AI()
	+ moveMessage()
	# minimax()
}

class EasyAI {
	- rand : Random
	+ EasyAI()
	+ chooseCoordinates()
}

class MediumAI {
	- rand : Random
	+ MediumAI()
	+ chooseCoordinates()
}

class HardAI {
	+ HardAI()
	+ chooseCoordinates()
}

class Board {
	- board : char
	+ isFree()
	+ getWinner()
	+ reset()
	+ printBoard()
}

class Main {
	- turn : int
	- board : Board
	- players : IPlayer
	+ main()
	- initPlayers()
}

class User {
	+ User()
	+ chooseCoordinates()
}

abstract class Player {
	- playerChar : char
	+ Player()
	+ getPlayerChar()
}

interface IPlayer {
	+ chooseCoordinates()
	+ getPlayerChar()
}

IPlayer <|-- Player
Player <|-- User
Player <|-- AI
AI <|-- EasyAI
AI <|-- MediumAI
AI <|-- HardAI
Main "2" o-- "*" IPlayer
Main "1" o-- "*" Board

@enduml